export const project = { id: 'sample', name: 'langchain_based_agent', path: '/sample/langchain_based_agent' };
export const threads = [
  { thread_id: 'conversation-1', metadata: { title: 'Explore the agent architecture', cwd: project.path }, status: 'idle' },
  { thread_id: 'conversation-2', metadata: { title: 'Memory design exploration', cwd: project.path }, status: 'idle' },
  { thread_id: 'conversation-3', metadata: { title: 'Review background task lifecycle', cwd: project.path }, status: 'idle' },
];
export const messages = [
  { id: 'human-1', type: 'human', content: 'Explore the memory components of this agent. How is it designed now, and where could we improve it?' },
  { id: 'ai-1', type: 'ai', content: 'I’ll trace how the agent loads its instructions, retains conversation context, and stores work between sessions.', tool_calls: [{ id: 'tool-1', name: 'read_file', args: { file_path: 'src/lc_factory/assembly.py' } }] },
  { id: 'tool-result', type: 'tool', tool_call_id: 'tool-1', name: 'read_file', content: 'The assembly composes workspace-scoped instructions, skill discovery, conversation persistence, and background task execution.' },
  { id: 'ai-2', type: 'ai', content: 'The system has two useful layers to think about.\n\n### Agent definition\nInstructions, skills, and linked guidance describe **how the agent works**. They’re designed ahead of time and loaded as needed.\n\n### Working memory\nConversation history, notes, task outcomes, and generated files capture **what the agent is working on**. Their lifecycles differ.\n\nI’ve started a focused review of the persistence boundaries. You can follow it in **Tasks** while we discuss the design.', usage_metadata: { input_tokens: 3240, output_tokens: 241 } },
];
export const snapshot = { values: { messages, _model_spec: 'anthropic:claude-sonnet-4-6', todos: [{ content: 'Trace instruction and skill discovery', status: 'completed' }, { content: 'Map generated state and retention', status: 'in_progress' }, { content: 'Compare retrieval improvements', status: 'pending' }] }, next: [], interrupts: [], checkpoint: { checkpoint_id: 'sample-checkpoint-1' } };
const sampleNow = Math.floor(Date.now() / 1000);
export const tasks = [
  { task_id: 'task-memory', name: 'Memory & persistence', description: 'Inspect conversation storage and the lifecycle of generated workspace state.', status: 'running', interrupts: [], steerable: true, queued_at: sampleNow - 160, started_at: sampleNow - 154, updated_at: sampleNow - 154, latest: { sequence: 4, kind: 'tool', tool_name: 'read_file', status: 'completed' } },
  { task_id: 'task-guidance', name: 'Instruction discovery', description: 'Map the skill catalog, linked guides, and always-loaded instructions.', status: 'completed', result: 'Skills use progressive disclosure; the catalog stays available and instructions load on demand.', interrupts: [], steerable: false, queued_at: sampleNow - 900, started_at: sampleNow - 890, updated_at: sampleNow - 620, finished_at: sampleNow - 620, acknowledged: true },
];
export const catalog = { model: 'anthropic:claude-sonnet-4-6', skills: [{ name: 'brainstorm', description: 'Explore the problem, compare options, and converge on a clear direction before implementation.', path: project.path + '/.agents/skills/brainstorm/SKILL.md', source: 'Project' }, { name: 'review', description: 'Review the actual implementation against its intent, then inspect correctness and maintainability.', path: project.path + '/.agents/skills/review/SKILL.md', source: 'Project' }, { name: 'piper-workflow', description: 'Carry a bounded implementation through verification, review, and completion.', path: project.path + '/.agents/skills/workflow/SKILL.md', source: 'Project' }], tools: [{ name: 'read_file', description: 'Read files within the active agent workspace.' }, { name: 'write_file', description: 'Write a file, subject to the current approval policy.' }, { name: 'run_background_tasks', description: 'Delegate independent work with visible status and retained results.' }], capabilities: { hooks: false } };
export const files = { path: '', entries: [{ name: '.agents', path: '.agents', directory: true }, { name: 'src', path: 'src', directory: true }, { name: 'AGENTS.md', path: 'AGENTS.md', directory: false }, { name: 'architecture.md', path: 'architecture.md', directory: false }, { name: 'README.md', path: 'README.md', directory: false }] };
export const artifact = { path: 'architecture.md', kind: 'markdown', size: 642, text: '# Agent memory architecture\n\nA workspace has two complementary kinds of memory.\n\n## Agent definition\n\n- Always-loaded project instructions\n- A discoverable skill catalog\n- Extended guidance loaded on demand\n\n## Generated state\n\n| State | Lifecycle |\n| --- | --- |\n| Conversation | Checkpointed |\n| Background task | Server session |\n| Workspace notes | Project files |\n\n> A graph can become a useful retrieval index while the original files retain their role as sources.\n' };
