"""Server-side graph entry point for ``langgraph dev`` (factory edition).

Port of ``deepagents_code.server_graph`` at commit
``6c89fe2197a2dfe4f3851cda38565bcadba6066b`` (version ``0.1.66``), whose
primary semantic change is that the agent graph is built by
:func:`lc_factory.assembly.create_factory_agent` instead of upstream's
``create_cli_agent``. The factory transport is resolved before provider or
sandbox setup, while upstream's config, tool discovery, extension lifecycle,
cached ``ServerRuntime``, and server-owned offload operation stay intact.

Referenced by the ``langgraph.json`` generated by :mod:`lc_factory.launch` as
``lc_factory.server_graph:make_graph``. The graph name stays ``"agent"`` and
the ``DEEPAGENTS_CODE_SERVER_*`` env contract is unchanged, so the upstream
TUI client works against this server without modification.
"""

from __future__ import annotations

import asyncio
import atexit
import dataclasses
import importlib
import logging
import os
import sys
from collections import OrderedDict
from collections.abc import Iterable, Mapping
from collections.abc import Set as AbstractSet
from pathlib import Path
from types import MappingProxyType
from typing import TYPE_CHECKING, Any

from lc_factory._env import MIDDLEWARE_REF_ENV, reserve_middleware_ref_env
from lc_factory.upstream import (
    CLIContextSchema,
    EXPERIMENTAL,
    ExtensionMode,
    InterpreterConfig,
    LangGraphServerRuntime,
    ProjectContext,
    STARTUP_ERROR_MARKER as _STARTUP_ERROR_MARKER,
    ServerConfig,
    ServerRuntime,
    WorkspaceConflictError,
    _build_runtime_factory,
    _build_tools,
    _criteria_context_tools,
    bind_server_extensions,
    configure_langsmith_secret_redaction,
    create_model,
    create_sandbox,
    emit_startup_failure,
    get_config_resolver,
    get_server_project_context,
    is_env_truthy,
    is_memory_auto_save_enabled,
    load_async_subagents,
    load_extensions,
    offload_operation_from,
    require_thread_workspace,
    resolve_workspace,
    resolve_auto_classifier_model_for_provider,
    shutdown_server_extensions,
)

if TYPE_CHECKING:
    from lc_factory.upstream import CredentialsSnapshot, ExtensionRegistry, WorkspaceBinding

logger = logging.getLogger(__name__)

_sandbox_cm: Any = None
_sandbox_backend: Any = None


def _resolve_middleware_ref(ref: str) -> Any:  # noqa: ANN401
    """Import and call the factory-middleware reference named by ``ref``.

    Args:
        ref: A ``"module.path:callable"`` string.

    Returns:
        The factory's result, normalized to ``{"main": ..., "subagents": ...,
        "grader": ...}`` — one phase mapping of materialized lists per target,
        each ready for the matching ``create_factory_agent`` parameter. See
        `_normalize_targets` for the accepted input shapes. Returning the
        *original* would silently drop one-shot iterables: normalization
        materializes them via ``list()``, so a generator would arrive
        downstream already exhausted and compose as empty.

    Raises:
        ValueError: For every failure THIS function detects — malformed
            reference, an import that fails or itself raises, a missing or
            unreadable attribute, a non-callable target, a factory that raises,
            or a return value that is not usable as middleware. Each is
            converted to this one type with the variable named, because it is
            set outside the app and nothing else in the traceback would point
            at it. Raised rather than warned so startup fails loudly: booting
            without the caller's middleware would serve a differently composed
            agent, silently.

            Failures raised *later*, by `create_factory_agent` validating the
            middleware itself (unknown phase, non-middleware entries, reserved
            or duplicate names), are not funnelled through here. They are
            self-describing and reach the user through upstream's own
            graph-factory error barrier.
    """
    module_name, separator, attribute = ref.partition(":")
    if not separator or not module_name or not attribute:
        msg = (
            f"{MIDDLEWARE_REF_ENV} must be 'module.path:callable'; got {ref!r}."
        )
        raise ValueError(msg)
    try:
        module = importlib.import_module(module_name)
    except Exception as exc:
        # Not just ImportError: the named module runs at import, so it can
        # raise anything. Attribution matters more than the class here.
        msg = (
            f"{MIDDLEWARE_REF_ENV}: cannot import module {module_name!r}: "
            f"{type(exc).__name__}: {exc}"
        )
        raise ValueError(msg) from exc
    try:
        factory = getattr(module, attribute)
    except AttributeError as exc:
        msg = (
            f"{MIDDLEWARE_REF_ENV}: module {module_name!r} has no attribute "
            f"{attribute!r}."
        )
        raise ValueError(msg) from exc
    except Exception as exc:
        # A module-level PEP 562 `__getattr__` can raise anything at all.
        msg = (
            f"{MIDDLEWARE_REF_ENV}: reading {attribute!r} from {module_name!r} "
            f"raised {type(exc).__name__}: {exc}"
        )
        raise ValueError(msg) from exc
    if not callable(factory):
        msg = f"{MIDDLEWARE_REF_ENV}: {ref!r} is not callable."
        raise ValueError(msg)
    try:
        result = factory()
    except Exception as exc:
        # A factory that takes arguments is the common case here; without this
        # the user sees a bare TypeError naming their function and nothing
        # connecting it to the variable they set.
        msg = f"{MIDDLEWARE_REF_ENV}: {ref!r} raised {type(exc).__name__}: {exc}"
        raise ValueError(msg) from exc
    if result is None:
        msg = (
            f"{MIDDLEWARE_REF_ENV}: {ref!r} returned None. A middleware factory "
            f"must return a sequence of middleware or a phase-keyed mapping; a "
            f"missing `return` is the usual cause. Returning nothing would "
            f"otherwise boot an agent composed without your middleware."
        )
        raise ValueError(msg)
    if isinstance(result, AbstractSet):
        # Ordering IS the seam's contract, and set iteration order varies with
        # PYTHONHASHSEED between server restarts. Accepting one would turn a
        # documented position into a coin flip that nothing downstream notices.
        # `{MyMiddleware()}` is also the natural typo for a phase mapping.
        msg = (
            f"{MIDDLEWARE_REF_ENV}: {ref!r} returned an unordered "
            f"{type(result).__name__}; middleware order is the seam's "
            f"contract. Return a list or a phase-keyed mapping."
        )
        raise ValueError(msg)
    if not isinstance(result, Iterable) or isinstance(result, (str, bytes)):
        msg = (
            f"{MIDDLEWARE_REF_ENV}: {ref!r} returned "
            f"{type(result).__name__}; expected a sequence of middleware or a "
            f"phase-keyed mapping."
        )
        raise ValueError(msg)

    # Validate the CONTENTS here too, not just the container. The assembly
    # would catch a bad phase key or a non-middleware entry anyway — but only
    # after `create_model`, MCP discovery and sandbox creation have run, so a
    # one-character phase typo could spin up a remote sandbox before failing.
    # Re-raised with the variable named, since that is the knob at fault.
    #
    # Return the NORMALIZED result, not the original: normalization
    # materializes one-shot iterables (`list()`), so a factory returning a
    # generator would otherwise be consumed right here and compose as empty
    # downstream — a silent drop, the exact failure this transport promises
    # cannot happen.
    return _normalize_targets(result, ref)


def _normalize_targets(result: Any, ref: str) -> dict[str, Any]:  # noqa: ANN401
    """Normalize a factory's return into per-target middleware mappings.

    Three accepted shapes, disambiguated by key rather than by guessing:

    - a bare sequence — main agent, default phase (the original form);
    - a **phase**-keyed mapping (`first`/`before_verification`/`last`) — main
      agent, explicit phases (also original);
    - a **target**-keyed mapping (`main`/`subagents`/`grader`) whose values are
      either of the above — added when Group 3's targets needed to reach
      `lc-code`.

    Target and phase keys are disjoint sets, which is what makes this safe to
    disambiguate. A mapping mixing both, or naming something in neither set, is
    **rejected rather than interpreted**: guessing would silently compose an
    agent the caller did not ask for, which is the failure class this whole
    transport exists to prevent.

    Reusing one variable is deliberate. A variable per target would each need
    its own `.env` reservation in `lc_factory/__init__.py` — resolving a
    reference imports and executes the named module inside the server process
    (decisions.md D4) — so every new name is new attack surface. This adds
    none: the existing reservation already covers it.

    Args:
        result: Whatever the referenced callable returned.
        ref: The reference string, for error attribution.

    Returns:
        `{"main": ..., "subagents": ..., "grader": ...}`, each a normalized
        phase mapping ready to hand to the matching `create_factory_agent`
        parameter.

    Raises:
        ValueError: For an unknown, mixed, or unusable shape — always naming
            the variable, since it is set outside the app.
    """
    from lc_factory.assembly import (
        _normalize_grader_middleware,
        _normalize_injected_middleware,
        _normalize_subagent_middleware,
    )

    normalizers = {
        "main": _normalize_injected_middleware,
        "subagents": _normalize_subagent_middleware,
        "grader": _normalize_grader_middleware,
    }

    per_target: dict[str, Any] = {}
    if isinstance(result, Mapping):
        keys = set(result)
        targets = keys & set(normalizers)
        if targets and targets != keys:
            msg = (
                f"{MIDDLEWARE_REF_ENV}: {ref!r} returned a mapping mixing "
                f"target keys {sorted(targets)} with {sorted(keys - targets)}. "
                f"Return either a target-keyed mapping "
                f"({sorted(normalizers)}) or a phase-keyed mapping for the "
                f"main agent — not both. Nesting is one level: put phases "
                f"inside a target."
            )
            raise ValueError(msg)
        if targets:
            per_target = dict(result)

    if not per_target:
        # No target keys: the whole value addresses the main agent, in either
        # of the two original forms. Unknown phase keys are caught below by the
        # main normalizer, whose message already lists the valid phases.
        per_target = {"main": result}

    resolved: dict[str, Any] = {}
    for target, normalize in normalizers.items():
        supplied = per_target.get(target)
        try:
            resolved[target] = normalize(supplied)
        except ValueError as exc:
            msg = (
                f"{MIDDLEWARE_REF_ENV}: {ref!r} returned unusable middleware "
                f"for target {target!r}: {exc}"
            )
            raise ValueError(msg) from exc
    return resolved


def _factory_middleware() -> Any:  # noqa: ANN401
    """Resolve caller-supplied middleware from the environment, if any.

    Returns:
        Per-target normalized middleware (see `_normalize_targets`), or
        ``None`` when the variable is unset or empty — which composes exactly
        as it did before the seam existed.
    """
    ref = os.environ.get(MIDDLEWARE_REF_ENV, "").strip()
    if not ref:
        return None
    return _resolve_middleware_ref(ref)


def _print_startup_error(message: str) -> None:
    """Print a startup error for both humans and the parent app process.

    Args:
        message: Concise startup failure to surface in the parent process.
    """
    print(message, file=sys.stderr)  # noqa: T201  # stderr fallback for logs
    summary = " ".join(message.splitlines()).strip() or "<no message>"
    print(  # noqa: T201  # machine-readable marker consumed by server.py
        f"{_STARTUP_ERROR_MARKER}{summary}",
        file=sys.stderr,
    )


async def _make_graphs(
    *,
    config_override: ServerConfig | None = None,
    project_context_override: ProjectContext | None = None,
) -> ServerRuntime:
    """Create the agent graph and the backend carrying its shared resources.

    Reads `DEEPAGENTS_CODE_SERVER_*` env vars via `ServerConfig.from_env()`
    (the inverse of `ServerConfig.to_env()` used by the app process), resolves a
    model, assembles tools, and compiles the agent graph.

    Returns:
        The agent graph, its configured composite backend, and the server-owned
            offload operation bound to that backend.
    """
    config = config_override or ServerConfig.from_env()
    from lc_factory.upstream import (
        Credentials,
        _preview_dotenv_environ,
        use_environment,
    )

    workspace_path = (
        project_context_override.user_cwd
        if project_context_override is not None
        else Path(config.cwd)
        if config.cwd is not None
        else None
    )

    # Offload the workspace environment snapshot off the event loop. Dotenv
    # discovery walks parent directories (`Path.resolve()`, `is_file()`) and
    # reads up to three files, and `snapshot_from_environment` adds
    # `find_project_root()` -> `Path.cwd()` — all of which `blockbuster`
    # rejects when invoked directly from the server loop (see issue #5043),
    # for the same reason as the offload in `_make_graphs_in_environment`.
    def _resolve_workspace_environment() -> tuple[
        Mapping[str, str], CredentialsSnapshot
    ]:
        environ = MappingProxyType(_preview_dotenv_environ(start_path=workspace_path))
        return environ, Credentials.snapshot_from_environment(
            start_path=workspace_path,
            environ=environ,
        )

    workspace_env, workspace_credentials = await asyncio.to_thread(
        _resolve_workspace_environment
    )

    with use_environment(workspace_env):
        return await _make_graphs_in_environment(
            config=config,
            project_context_override=project_context_override,
            workspace_env=workspace_env,
            workspace_credentials=workspace_credentials,
        )


async def _make_graphs_in_environment(
    *,
    config: ServerConfig,
    project_context_override: ProjectContext | None,
    workspace_env: Mapping[str, str],
    workspace_credentials: CredentialsSnapshot,
) -> ServerRuntime:
    """Build the factory graph inside its immutable workspace environment."""
    from lc_factory.assembly import create_factory_agent

    # Path resolution can perform blocking filesystem IO.
    def _resolve_project_context() -> ProjectContext | None:
        project_context = project_context_override or get_server_project_context()
        return project_context

    project_context = await asyncio.to_thread(
        _resolve_project_context
    )
    configure_langsmith_secret_redaction()

    # Resolve the caller seam before model setup, MCP discovery, or sandbox
    # creation. Booting without requested middleware is never a fallback.
    try:
        injected_middleware = _factory_middleware()
    except ValueError as exc:
        logger.exception("Invalid %s", MIDDLEWARE_REF_ENV)
        _print_startup_error(str(exc))
        sys.exit(1)

    result = await asyncio.to_thread(
        create_model,
        config.model,
        extra_kwargs=config.model_params,
        profile_overrides=config.profile_overrides,
        cli_max_retries=config.cli_max_retries,
    )
    result.apply_to_runtime_state()

    tools, mcp_server_info, mcp_tools = await _build_tools(
        config,
        project_context,
        has_tavily=workspace_credentials.has_tavily,
        tavily_api_key=workspace_credentials.tavily_api_key,
    )
    read_only_context_tools = _criteria_context_tools(tools, mcp_tools)

    global _sandbox_cm, _sandbox_backend  # noqa: PLW0603
    sandbox_backend = None
    if config.sandbox_type:
        try:
            _sandbox_cm = create_sandbox(
                config.sandbox_type,
                sandbox_id=config.sandbox_id,
                snapshot_name=config.sandbox_snapshot_name,
                setup_script_path=config.sandbox_setup,
            )
            _sandbox_backend = _sandbox_cm.__enter__()  # noqa: PLC2801
            sandbox_backend = _sandbox_backend

            def _cleanup_sandbox() -> None:
                if _sandbox_cm is not None:
                    _sandbox_cm.__exit__(None, None, None)

            atexit.register(_cleanup_sandbox)
        except ImportError:
            logger.exception(
                "Sandbox provider '%s' is not installed", config.sandbox_type
            )
            _print_startup_error(
                f"Sandbox provider '{config.sandbox_type}' is not installed"
            )
            sys.exit(1)
        except NotImplementedError:
            logger.exception("Sandbox type '%s' is not supported", config.sandbox_type)
            _print_startup_error(
                f"Sandbox type '{config.sandbox_type}' is not supported"
            )
            sys.exit(1)
        except ValueError as exc:
            logger.exception(
                "Invalid sandbox configuration for '%s'", config.sandbox_type
            )
            _print_startup_error(f"Invalid sandbox configuration: {exc}")
            sys.exit(1)
        except Exception as exc:
            logger.exception("Sandbox creation failed for '%s'", config.sandbox_type)
            _print_startup_error(
                f"Sandbox creation failed for '{config.sandbox_type}': {exc}"
            )
            sys.exit(1)

    extension_registry: ExtensionRegistry | None = None

    def _create_factory_runtime_sync() -> ServerRuntime:
        targets = injected_middleware or {}
        async_subagents = load_async_subagents() or None
        auto_mode_enabled = config.interactive and sandbox_backend is None
        interpreter_config = (
            InterpreterConfig.from_resolver(
                get_config_resolver(),
                ptc=config.interpreter_ptc,
                ptc_acknowledge_unsafe=config.interpreter_ptc_acknowledge_unsafe,
            )
            if config.enable_interpreter
            else None
        )

        agent, composite_backend = create_factory_agent(
            model=result.model,
            assistant_id=config.assistant_id,
            tools=tools,
            mcp_tools=mcp_tools,
            sandbox=sandbox_backend,
            sandbox_type=config.sandbox_type,
            system_prompt=config.system_prompt,
            interactive=config.interactive,
            auto_approve=config.auto_approve,
            auto_mode_enabled=auto_mode_enabled,
            interrupt_shell_only=config.interrupt_shell_only,
            shell_allow_list=config.shell_allow_list,
            fs_tools=config.allow_fs_tools,
            enable_ask_user=config.enable_ask_user,
            enable_memory=config.enable_memory,
            memory_auto_save=is_memory_auto_save_enabled(),
            enable_skills=config.enable_skills,
            enable_shell=config.enable_shell,
            enable_interpreter=config.enable_interpreter,
            interpreter_config=interpreter_config,
            rubric_model=config.rubric_model,
            rubric_max_iterations=config.rubric_max_iterations,
            auto_classifier_model=resolve_auto_classifier_model_for_provider(
                result.provider,
                config.auto_classifier_model,
            ),
            recursion_limit=config.recursion_limit,
            mcp_server_info=mcp_server_info,
            cwd=project_context.user_cwd if project_context is not None else config.cwd,
            project_context=project_context,
            async_subagents=async_subagents,
            goal_criteria_tools=read_only_context_tools,
            rubric_grader_tools=read_only_context_tools,
            model_retries=result.model_retries,
            cli_max_retries=result.cli_max_retries,
            summarization_model=config.summarization_model,
            extension_registry=extension_registry,
            environ=workspace_env,
            credentials_snapshot=workspace_credentials,
            model_result=result,
            # All three targets remain reachable through the one reserved
            # process-boundary variable.
            middleware=targets.get("main"),
            subagent_middleware=targets.get("subagents"),
            rubric_grader_middleware=targets.get("grader"),
        )
        offload = offload_operation_from(composite_backend)
        if offload is None:
            msg = (
                "Agent backend did not publish its offload operation; "
                "/offload has no server implementation."
            )
            raise RuntimeError(msg)
        return ServerRuntime(
            agent=agent,
            backend=composite_backend,
            offload=offload,
        )

    if is_env_truthy(EXPERIMENTAL, environ=workspace_env):
        extension_result = await load_extensions(
            cwd=(
                project_context.user_cwd
                if project_context is not None
                else Path(config.cwd)
                if config.cwd is not None
                else None
            ),
            mode=(
                ExtensionMode.INTERACTIVE
                if config.interactive
                else ExtensionMode.HEADLESS
            ),
            project_root=(
                project_context.project_root or project_context.user_cwd
                if project_context is not None
                else None
            ),
            project_trust_granted=config.trust_project_extensions,
            cli_paths=tuple(Path(path) for path in config.extension_paths),
        )
        for message in extension_result.errors:
            logger.warning("Extension not loaded: %s", message)
        if extension_result.active:
            extension_registry = extension_result.registry
            bind_server_extensions(extension_result)
    try:
        return await asyncio.to_thread(_create_factory_runtime_sync)
    except BaseException:
        if extension_registry is not None:
            await shutdown_server_extensions()
        raise


_get_runtime = _build_runtime_factory(_make_graphs)
_MAX_WORKSPACE_RUNTIMES = 32
_workspace_runtimes: OrderedDict[str, ServerRuntime] = OrderedDict()
_workspace_runtime_lock = asyncio.Lock()
_sandbox_workspace_id: str | None = None


def _cached_workspace_runtime(binding: WorkspaceBinding) -> ServerRuntime | None:
    """Return and refresh a cached runtime for one workspace binding."""
    cached = _workspace_runtimes.get(binding.resource_key)
    if cached is None:
        return None
    _workspace_runtimes.move_to_end(binding.resource_key)
    return cached


def _claim_sandbox_workspace(
    sandbox_type: str | None,
    binding: WorkspaceBinding,
) -> None:
    """Reserve the process-wide sandbox for the first requesting workspace."""
    global _sandbox_workspace_id  # noqa: PLW0603  # process-lifetime ownership
    if not sandbox_type:
        return
    if _sandbox_workspace_id is None:
        _sandbox_workspace_id = binding.workspace_id
        return
    if _sandbox_workspace_id == binding.workspace_id:
        return
    reason = (
        "a runtime for another workspace already exists and the configured "
        "sandbox is process-wide"
    )
    # Built into a local first: `raise X.from_reason(...)` reads as a
    # `from_reason` raise to ruff's DOC501.
    conflict = WorkspaceConflictError.from_reason(reason)
    raise conflict


def _remember_workspace_runtime(
    binding: WorkspaceBinding,
    runtime: ServerRuntime,
) -> None:
    """Cache one workspace runtime and enforce the bounded LRU size."""
    _workspace_runtimes[binding.resource_key] = runtime
    if len(_workspace_runtimes) > _MAX_WORKSPACE_RUNTIMES:
        _workspace_runtimes.popitem(last=False)


async def _default_workspace_binding(config: ServerConfig) -> WorkspaceBinding | None:
    """Resolve the launch workspace represented by the server configuration.

    Returns:
        The canonical launch binding, or `None` without a configured workspace.
    """
    if config.cwd is None:
        return None
    return await asyncio.to_thread(
        resolve_workspace,
        config.cwd,
        config.to_workspace_payload(),
        config_fingerprint=config.workspace_fingerprint(),
    )


async def _workspace_runtime(binding: WorkspaceBinding) -> ServerRuntime:
    """Build or reuse a runtime from the persisted workspace resource policy.

    Returns:
        The runtime selected by the binding's immutable resource key.
    """
    cached = _cached_workspace_runtime(binding)
    if cached is not None:
        return cached
    async with _workspace_runtime_lock:
        cached = _cached_workspace_runtime(binding)
        if cached is not None:
            return cached
        config = ServerConfig.from_env()
        current_config = dataclasses.replace(
            config,
            cwd=binding.cwd,
            project_root=binding.project_root,
        )
        if (
            current_config.workspace_fingerprint() != binding.config_fingerprint
            or current_config.to_workspace_payload() != binding.workspace_config()
        ):
            reason = "the server configuration changed after this workspace was bound"
            # Built into a local first: `raise X.from_reason(...)` reads as a
            # `from_reason` raise to ruff's DOC501.
            conflict = WorkspaceConflictError.from_reason(reason)
            raise conflict
        _claim_sandbox_workspace(current_config.sandbox_type, binding)
        project_context = ProjectContext(
            user_cwd=Path(binding.cwd),
            project_root=Path(binding.project_root) if binding.project_root else None,
        )
        runtime = await _make_graphs(
            config_override=current_config,
            project_context_override=project_context,
        )
        _remember_workspace_runtime(binding, runtime)
        return runtime


async def get_server_runtime() -> ServerRuntime:
    """Return resources shared by the graph and dcode operation routes.

    Builds once and caches. A construction failure is converted into a
    startup-error marker (scraped by the parent app process) before
    `sys.exit(1)`, which is right for the `langgraph.json` graph factory at
    startup. Callers in request scope must contain that exit -- `SystemExit` is a
    `BaseException` -- as `offload_api._execute_offload` does, mapping it to a 503
    rather than killing the server mid-request.

    Returns:
        The cached server runtime.
    """
    # Resolving the launch binding touches the filesystem and can raise, and
    # claiming the sandbox can refuse. Both run before `_get_runtime`, so they
    # sit outside its startup barrier and would exit without the marker the
    # parent app process scrapes. Emit it here instead.
    try:
        config = ServerConfig.from_env()
        binding = await _default_workspace_binding(config)
    except Exception as exc:  # noqa: BLE001  # startup barrier
        emit_startup_failure(exc)
        sys.exit(1)
    async with _workspace_runtime_lock:
        if binding is None:
            return await _get_runtime()
        cached = _cached_workspace_runtime(binding)
        if cached is not None:
            return cached
        _claim_sandbox_workspace(config.sandbox_type, binding)
        runtime = await _get_runtime()
        _remember_workspace_runtime(binding, runtime)
        return runtime


async def make_graph(
    config: dict[str, Any] | None = None,
    runtime: LangGraphServerRuntime[CLIContextSchema] | None = None,
) -> Any:  # noqa: ANN401
    """Return the graph after validating execution workspace context.

    Raises:
        ValueError: If execution context is missing or malformed.
    """
    execution = runtime.execution_runtime if runtime is not None else None
    if execution is not None:
        context = CLIContextSchema.from_payload(execution.context)
        thread_id = (config or {}).get("configurable", {}).get("thread_id")
        if context is None or not isinstance(thread_id, str) or not thread_id:
            msg = "A thread id and workspace context are required for execution."
            raise ValueError(msg)
        from lc_factory.upstream import require_thread_workspace

        binding = await require_thread_workspace(thread_id, context.workspace)
        return (await _workspace_runtime(binding)).agent
    return (await get_server_runtime()).agent
