"""Server-side graph entry point for ``langgraph dev`` (factory edition).

Port of ``deepagents_code.server_graph`` (monorepo ``8da0ccb13``) whose only
semantic change is that the agent graph is built by
:func:`lc_factory.assembly.create_factory_agent` instead of upstream's
``create_cli_agent``. Config parsing, tool assembly (including MCP discovery),
and the cached graph-factory pattern are reused from upstream through the
boundary module.

Referenced by the ``langgraph.json`` generated by :mod:`lc_factory.launch` as
``lc_factory.server_graph:make_graph``. The graph name stays ``"agent"`` and
the ``DEEPAGENTS_CODE_SERVER_*`` env contract is unchanged, so the upstream
TUI client works against this server without modification.
"""

from __future__ import annotations

import asyncio
import atexit
import importlib
import logging
import os
import sys
from collections.abc import Iterable
from collections.abc import Set as AbstractSet
from typing import Any

from lc_factory.upstream import (
    STARTUP_ERROR_MARKER as _STARTUP_ERROR_MARKER,
    ServerConfig,
    _build_graph_factory,
    _build_tools,
    _criteria_context_tools,
    configure_langsmith_secret_redaction,
    create_model,
    create_sandbox,
    get_server_project_context,
    is_memory_auto_save_enabled,
    load_async_subagents,
    settings,
)

logger = logging.getLogger(__name__)

_sandbox_cm: Any = None
_sandbox_backend: Any = None

MIDDLEWARE_REF_ENV = "LC_FACTORY_MIDDLEWARE"
"""Env var naming a zero-argument callable that supplies factory middleware.

Format is ``"module.path:callable"`` — the same shape upstream already uses for
``graph_ref``, ``checkpointer_path``, and model ``class_path``. The callable's
return value is passed straight to ``create_factory_agent(middleware=...)``, so
it may be a bare sequence or a phase-keyed mapping; choosing phases stays in
Python rather than being encoded into a string.

Resolving it imports and executes the named module inside the server process,
so it must come from a **real shell export**: a project-local source would mean
that entering an untrusted repository and running ``lc-code`` executes that
repository's code before any approval gate (decisions.md D4).

Reading ``os.environ`` is *not* by itself sufficient for that — upstream loads
``.env`` files straight into it, on two paths that both run before resolution.
:func:`reserve_middleware_ref_env` is what actually holds the invariant; read
its docstring before changing anything here, and do not add a file-based
source without an explicit trust design.

Deliberately outside ``ServerConfig``: upstream's ``DEEPAGENTS_CODE_SERVER_*``
contract stays byte-identical, and ``_build_server_env`` relays this variable
to the subprocess on every start and restart because it filters by an explicit
denylist rather than by prefix.
"""


def reserve_middleware_ref_env() -> None:
    """Claim ``LC_FACTORY_MIDDLEWARE`` so no ``.env`` file can introduce it.

    This is what actually enforces the user-scoped invariant, and it must run
    before anything touches ``settings``.

    Upstream loads ``.env`` files into ``os.environ`` on two paths that both
    precede resolution: the client's settings bootstrap searches upward from
    the cwd, and the server's ``settings.reload_from_environment`` re-reads the
    project directory. Either would let a **committed** ``.env`` in a cloned
    repository name a module for the server to import and call — the exact
    thing decisions.md D4 forbids, and the reason upstream keeps its own
    denylist of keys that "turn `.env` loading into code execution". That
    denylist is a `frozenset` and cannot be extended, and it cannot know about
    this variable anyway.

    So instead of filtering the loader, this occupies the slot: upstream's
    ``apply_dotenv`` skips any key already present in ``os.environ``, so a
    pre-set value — even an empty one, which reads as "unset" — makes the
    variable unsettable from any ``.env``. Consequence worth knowing: the
    variable is then settable **only** from a real shell export, including in
    the user's own global ``~/.deepagents/.env``. Distinguishing a global
    ``.env`` from a project one needs upstream internals we deliberately do not
    reach for; refusing both is the safe direction and is documented.
    """
    os.environ.setdefault(MIDDLEWARE_REF_ENV, "")


def _resolve_middleware_ref(ref: str) -> Any:  # noqa: ANN401
    """Import and call the factory-middleware reference named by ``ref``.

    Args:
        ref: A ``"module.path:callable"`` string.

    Returns:
        Whatever the referenced callable returns, to be handed to
        ``create_factory_agent(middleware=...)`` unchanged.

    Raises:
        ValueError: For every failure THIS function detects — malformed
            reference, an import that fails or itself raises, a missing or
            unreadable attribute, a non-callable target, a factory that raises,
            or a return value that is not usable as middleware. Each is
            converted to this one type with the variable named, because it is
            set outside the app and nothing else in the traceback would point
            at it. Raised rather than warned so startup fails loudly: booting
            without the caller's middleware would serve a differently composed
            agent, silently.

            Failures raised *later*, by `create_factory_agent` validating the
            middleware itself (unknown phase, non-middleware entries, reserved
            or duplicate names), are not funnelled through here. They are
            self-describing and reach the user through upstream's own
            graph-factory error barrier.
    """
    module_name, separator, attribute = ref.partition(":")
    if not separator or not module_name or not attribute:
        msg = (
            f"{MIDDLEWARE_REF_ENV} must be 'module.path:callable'; got {ref!r}."
        )
        raise ValueError(msg)
    try:
        module = importlib.import_module(module_name)
    except Exception as exc:
        # Not just ImportError: the named module runs at import, so it can
        # raise anything. Attribution matters more than the class here.
        msg = (
            f"{MIDDLEWARE_REF_ENV}: cannot import module {module_name!r}: "
            f"{type(exc).__name__}: {exc}"
        )
        raise ValueError(msg) from exc
    try:
        factory = getattr(module, attribute)
    except AttributeError as exc:
        msg = (
            f"{MIDDLEWARE_REF_ENV}: module {module_name!r} has no attribute "
            f"{attribute!r}."
        )
        raise ValueError(msg) from exc
    except Exception as exc:
        # A module-level PEP 562 `__getattr__` can raise anything at all.
        msg = (
            f"{MIDDLEWARE_REF_ENV}: reading {attribute!r} from {module_name!r} "
            f"raised {type(exc).__name__}: {exc}"
        )
        raise ValueError(msg) from exc
    if not callable(factory):
        msg = f"{MIDDLEWARE_REF_ENV}: {ref!r} is not callable."
        raise ValueError(msg)
    try:
        result = factory()
    except Exception as exc:
        # A factory that takes arguments is the common case here; without this
        # the user sees a bare TypeError naming their function and nothing
        # connecting it to the variable they set.
        msg = f"{MIDDLEWARE_REF_ENV}: {ref!r} raised {type(exc).__name__}: {exc}"
        raise ValueError(msg) from exc
    if result is None:
        msg = (
            f"{MIDDLEWARE_REF_ENV}: {ref!r} returned None. A middleware factory "
            f"must return a sequence of middleware or a phase-keyed mapping; a "
            f"missing `return` is the usual cause. Returning nothing would "
            f"otherwise boot an agent composed without your middleware."
        )
        raise ValueError(msg)
    if isinstance(result, AbstractSet):
        # Ordering IS the seam's contract, and set iteration order varies with
        # PYTHONHASHSEED between server restarts. Accepting one would turn a
        # documented position into a coin flip that nothing downstream notices.
        # `{MyMiddleware()}` is also the natural typo for a phase mapping.
        msg = (
            f"{MIDDLEWARE_REF_ENV}: {ref!r} returned an unordered "
            f"{type(result).__name__}; middleware order is the seam's "
            f"contract. Return a list or a phase-keyed mapping."
        )
        raise ValueError(msg)
    if not isinstance(result, Iterable) or isinstance(result, (str, bytes)):
        msg = (
            f"{MIDDLEWARE_REF_ENV}: {ref!r} returned "
            f"{type(result).__name__}; expected a sequence of middleware or a "
            f"phase-keyed mapping."
        )
        raise ValueError(msg)

    # Validate the CONTENTS here too, not just the container. The assembly
    # would catch a bad phase key or a non-middleware entry anyway — but only
    # after `create_model`, MCP discovery and sandbox creation have run, so a
    # one-character phase typo could spin up a remote sandbox before failing.
    # Re-raised with the variable named, since that is the knob at fault.
    from lc_factory.assembly import _normalize_injected_middleware

    try:
        _normalize_injected_middleware(result)
    except ValueError as exc:
        msg = f"{MIDDLEWARE_REF_ENV}: {ref!r} returned unusable middleware: {exc}"
        raise ValueError(msg) from exc
    return result


def _factory_middleware() -> Any:  # noqa: ANN401
    """Resolve caller-supplied middleware from the environment, if any.

    Returns:
        The referenced callable's result, or ``None`` when the variable is
        unset or empty — which composes exactly as it did before the seam
        existed.
    """
    ref = os.environ.get(MIDDLEWARE_REF_ENV, "").strip()
    if not ref:
        return None
    return _resolve_middleware_ref(ref)


def _print_startup_error(message: str) -> None:
    """Print a startup error for both humans and the parent app process.

    Args:
        message: Concise startup failure to surface in the parent process.
    """
    print(message, file=sys.stderr)  # noqa: T201  # stderr fallback for logs
    print(  # noqa: T201  # machine-readable marker consumed by server.py
        f"{_STARTUP_ERROR_MARKER}{message}",
        file=sys.stderr,
    )


async def _make_graph() -> Any:  # noqa: ANN401
    """Create the factory agent graph from environment-based configuration.

    Port of upstream ``server_graph._make_graph``: reads
    ``DEEPAGENTS_CODE_SERVER_*`` env vars via ``ServerConfig.from_env()``,
    resolves a model, assembles tools (reusing upstream's ``_build_tools``,
    which handles MCP discovery on the server loop), and compiles the agent
    graph via ``create_factory_agent``.

    Returns:
        Compiled LangGraph agent graph.
    """
    from lc_factory.assembly import create_factory_agent

    config = ServerConfig.from_env()
    project_context = get_server_project_context()

    if project_context is not None:
        settings.reload_from_environment(start_path=project_context.user_cwd)
    configure_langsmith_secret_redaction()

    # Resolved before the model is built so a bad reference fails in a second
    # rather than after provider setup. A failure here must stop the server:
    # booting without the caller's middleware would serve a differently
    # composed agent than they asked for, silently.
    try:
        injected_middleware = _factory_middleware()
    except ValueError as exc:
        logger.exception("Invalid %s", MIDDLEWARE_REF_ENV)
        _print_startup_error(str(exc))
        sys.exit(1)

    # Offload to a worker thread: `create_model` does blocking disk IO for
    # some providers, which `blockbuster` rejects on the server event loop.
    result = await asyncio.to_thread(
        create_model,
        config.model,
        extra_kwargs=config.model_params,
        profile_overrides=config.profile_overrides,
    )
    result.apply_to_settings()

    tools, mcp_server_info, mcp_tools = await _build_tools(config, project_context)
    read_only_context_tools = _criteria_context_tools(tools, mcp_tools)

    # Sandbox lifetime is process-scoped: the context manager is held in
    # module globals and cleaned up via atexit, exactly as upstream does.
    global _sandbox_cm, _sandbox_backend  # noqa: PLW0603
    sandbox_backend = None
    if config.sandbox_type:
        try:
            _sandbox_cm = create_sandbox(
                config.sandbox_type,
                sandbox_id=config.sandbox_id,
                snapshot_name=config.sandbox_snapshot_name,
                setup_script_path=config.sandbox_setup,
            )
            _sandbox_backend = _sandbox_cm.__enter__()  # noqa: PLC2801  # Context manager kept open for server process lifetime
            sandbox_backend = _sandbox_backend

            def _cleanup_sandbox() -> None:
                if _sandbox_cm is not None:
                    _sandbox_cm.__exit__(None, None, None)

            atexit.register(_cleanup_sandbox)
        except ImportError:
            logger.exception(
                "Sandbox provider '%s' is not installed", config.sandbox_type
            )
            _print_startup_error(
                f"Sandbox provider '{config.sandbox_type}' is not installed"
            )
            sys.exit(1)
        except NotImplementedError:
            logger.exception("Sandbox type '%s' is not supported", config.sandbox_type)
            _print_startup_error(
                f"Sandbox type '{config.sandbox_type}' is not supported"
            )
            sys.exit(1)
        except ValueError as exc:
            logger.exception(
                "Invalid sandbox configuration for '%s'", config.sandbox_type
            )
            _print_startup_error(f"Invalid sandbox configuration: {exc}")
            sys.exit(1)
        except Exception as exc:
            logger.exception("Sandbox creation failed for '%s'", config.sandbox_type)
            _print_startup_error(
                f"Sandbox creation failed for '{config.sandbox_type}': {exc}"
            )
            sys.exit(1)

    def _create_factory_agent_sync() -> Any:  # noqa: ANN401
        async_subagents = load_async_subagents() or None
        auto_mode_enabled = config.interactive and sandbox_backend is None

        # These process-global settings writes are safe here because
        # `make_graph` is lock-serialized and caches one graph for the server
        # process lifetime.
        if config.interpreter_ptc is not None:
            settings.interpreter_ptc = config.interpreter_ptc
        if config.interpreter_ptc_acknowledge_unsafe:
            settings.interpreter_ptc_acknowledge_unsafe = True
        if config.enable_interpreter:
            settings.enable_interpreter = True

        agent, _composite_backend = create_factory_agent(
            model=result.model,
            assistant_id=config.assistant_id,
            tools=tools,
            mcp_tools=mcp_tools,
            sandbox=sandbox_backend,
            sandbox_type=config.sandbox_type,
            system_prompt=config.system_prompt,
            interactive=config.interactive,
            auto_approve=config.auto_approve,
            auto_mode_enabled=auto_mode_enabled,
            interrupt_shell_only=config.interrupt_shell_only,
            shell_allow_list=config.shell_allow_list,
            fs_tools=config.allow_fs_tools,
            enable_ask_user=config.enable_ask_user,
            enable_memory=config.enable_memory,
            memory_auto_save=is_memory_auto_save_enabled(),
            enable_skills=config.enable_skills,
            enable_shell=config.enable_shell,
            enable_interpreter=config.enable_interpreter,
            rubric_model=config.rubric_model,
            rubric_max_iterations=config.rubric_max_iterations,
            recursion_limit=config.recursion_limit,
            mcp_server_info=mcp_server_info,
            cwd=project_context.user_cwd if project_context is not None else config.cwd,
            project_context=project_context,
            async_subagents=async_subagents,
            goal_criteria_tools=read_only_context_tools,
            rubric_grader_tools=read_only_context_tools,
            middleware=injected_middleware,
        )
        return agent

    return await asyncio.to_thread(_create_factory_agent_sync)


# Runs at import, which precedes every `settings` access in the server process
# and therefore every `.env` load. See the function's docstring.
reserve_middleware_ref_env()

make_graph = _build_graph_factory(_make_graph)
