"""Server-side graph entry point for ``langgraph dev`` (factory edition).

Port of ``deepagents_code.server_graph`` (monorepo ``8da0ccb13``, re-applied
for 0.1.52's off-loop settings bootstrap) whose only semantic change is that
the agent graph is built by
:func:`lc_factory.assembly.create_factory_agent` instead of upstream's
``create_cli_agent``. Config parsing, tool assembly (including MCP discovery),
and the cached graph-factory pattern are reused from upstream through the
boundary module.

Referenced by the ``langgraph.json`` generated by :mod:`lc_factory.launch` as
``lc_factory.server_graph:make_graph``. The graph name stays ``"agent"`` and
the ``DEEPAGENTS_CODE_SERVER_*`` env contract is unchanged, so the upstream
TUI client works against this server without modification.
"""

from __future__ import annotations

import asyncio
import atexit
import importlib
import logging
import os
import sys
from collections.abc import Iterable, Mapping
from collections.abc import Set as AbstractSet
from typing import Any

from lc_factory._env import MIDDLEWARE_REF_ENV, reserve_middleware_ref_env
from lc_factory.upstream import (
    ProjectContext,
    STARTUP_ERROR_MARKER as _STARTUP_ERROR_MARKER,
    ServerConfig,
    _build_graph_factory,
    _build_tools,
    _criteria_context_tools,
    configure_langsmith_secret_redaction,
    create_model,
    create_sandbox,
    get_server_project_context,
    is_memory_auto_save_enabled,
    load_async_subagents,
    settings,
)

logger = logging.getLogger(__name__)

_sandbox_cm: Any = None
_sandbox_backend: Any = None


def _resolve_middleware_ref(ref: str) -> Any:  # noqa: ANN401
    """Import and call the factory-middleware reference named by ``ref``.

    Args:
        ref: A ``"module.path:callable"`` string.

    Returns:
        The factory's result, normalized to ``{"main": ..., "subagents": ...,
        "grader": ...}`` — one phase mapping of materialized lists per target,
        each ready for the matching ``create_factory_agent`` parameter. See
        `_normalize_targets` for the accepted input shapes. Returning the
        *original* would silently drop one-shot iterables: normalization
        materializes them via ``list()``, so a generator would arrive
        downstream already exhausted and compose as empty.

    Raises:
        ValueError: For every failure THIS function detects — malformed
            reference, an import that fails or itself raises, a missing or
            unreadable attribute, a non-callable target, a factory that raises,
            or a return value that is not usable as middleware. Each is
            converted to this one type with the variable named, because it is
            set outside the app and nothing else in the traceback would point
            at it. Raised rather than warned so startup fails loudly: booting
            without the caller's middleware would serve a differently composed
            agent, silently.

            Failures raised *later*, by `create_factory_agent` validating the
            middleware itself (unknown phase, non-middleware entries, reserved
            or duplicate names), are not funnelled through here. They are
            self-describing and reach the user through upstream's own
            graph-factory error barrier.
    """
    module_name, separator, attribute = ref.partition(":")
    if not separator or not module_name or not attribute:
        msg = (
            f"{MIDDLEWARE_REF_ENV} must be 'module.path:callable'; got {ref!r}."
        )
        raise ValueError(msg)
    try:
        module = importlib.import_module(module_name)
    except Exception as exc:
        # Not just ImportError: the named module runs at import, so it can
        # raise anything. Attribution matters more than the class here.
        msg = (
            f"{MIDDLEWARE_REF_ENV}: cannot import module {module_name!r}: "
            f"{type(exc).__name__}: {exc}"
        )
        raise ValueError(msg) from exc
    try:
        factory = getattr(module, attribute)
    except AttributeError as exc:
        msg = (
            f"{MIDDLEWARE_REF_ENV}: module {module_name!r} has no attribute "
            f"{attribute!r}."
        )
        raise ValueError(msg) from exc
    except Exception as exc:
        # A module-level PEP 562 `__getattr__` can raise anything at all.
        msg = (
            f"{MIDDLEWARE_REF_ENV}: reading {attribute!r} from {module_name!r} "
            f"raised {type(exc).__name__}: {exc}"
        )
        raise ValueError(msg) from exc
    if not callable(factory):
        msg = f"{MIDDLEWARE_REF_ENV}: {ref!r} is not callable."
        raise ValueError(msg)
    try:
        result = factory()
    except Exception as exc:
        # A factory that takes arguments is the common case here; without this
        # the user sees a bare TypeError naming their function and nothing
        # connecting it to the variable they set.
        msg = f"{MIDDLEWARE_REF_ENV}: {ref!r} raised {type(exc).__name__}: {exc}"
        raise ValueError(msg) from exc
    if result is None:
        msg = (
            f"{MIDDLEWARE_REF_ENV}: {ref!r} returned None. A middleware factory "
            f"must return a sequence of middleware or a phase-keyed mapping; a "
            f"missing `return` is the usual cause. Returning nothing would "
            f"otherwise boot an agent composed without your middleware."
        )
        raise ValueError(msg)
    if isinstance(result, AbstractSet):
        # Ordering IS the seam's contract, and set iteration order varies with
        # PYTHONHASHSEED between server restarts. Accepting one would turn a
        # documented position into a coin flip that nothing downstream notices.
        # `{MyMiddleware()}` is also the natural typo for a phase mapping.
        msg = (
            f"{MIDDLEWARE_REF_ENV}: {ref!r} returned an unordered "
            f"{type(result).__name__}; middleware order is the seam's "
            f"contract. Return a list or a phase-keyed mapping."
        )
        raise ValueError(msg)
    if not isinstance(result, Iterable) or isinstance(result, (str, bytes)):
        msg = (
            f"{MIDDLEWARE_REF_ENV}: {ref!r} returned "
            f"{type(result).__name__}; expected a sequence of middleware or a "
            f"phase-keyed mapping."
        )
        raise ValueError(msg)

    # Validate the CONTENTS here too, not just the container. The assembly
    # would catch a bad phase key or a non-middleware entry anyway — but only
    # after `create_model`, MCP discovery and sandbox creation have run, so a
    # one-character phase typo could spin up a remote sandbox before failing.
    # Re-raised with the variable named, since that is the knob at fault.
    #
    # Return the NORMALIZED result, not the original: normalization
    # materializes one-shot iterables (`list()`), so a factory returning a
    # generator would otherwise be consumed right here and compose as empty
    # downstream — a silent drop, the exact failure this transport promises
    # cannot happen.
    return _normalize_targets(result, ref)


def _normalize_targets(result: Any, ref: str) -> dict[str, Any]:  # noqa: ANN401
    """Normalize a factory's return into per-target middleware mappings.

    Three accepted shapes, disambiguated by key rather than by guessing:

    - a bare sequence — main agent, default phase (the original form);
    - a **phase**-keyed mapping (`first`/`before_verification`/`last`) — main
      agent, explicit phases (also original);
    - a **target**-keyed mapping (`main`/`subagents`/`grader`) whose values are
      either of the above — added when Group 3's targets needed to reach
      `lc-code`.

    Target and phase keys are disjoint sets, which is what makes this safe to
    disambiguate. A mapping mixing both, or naming something in neither set, is
    **rejected rather than interpreted**: guessing would silently compose an
    agent the caller did not ask for, which is the failure class this whole
    transport exists to prevent.

    Reusing one variable is deliberate. A variable per target would each need
    its own `.env` reservation in `lc_factory/__init__.py` — resolving a
    reference imports and executes the named module inside the server process
    (decisions.md D4) — so every new name is new attack surface. This adds
    none: the existing reservation already covers it.

    Args:
        result: Whatever the referenced callable returned.
        ref: The reference string, for error attribution.

    Returns:
        `{"main": ..., "subagents": ..., "grader": ...}`, each a normalized
        phase mapping ready to hand to the matching `create_factory_agent`
        parameter.

    Raises:
        ValueError: For an unknown, mixed, or unusable shape — always naming
            the variable, since it is set outside the app.
    """
    from lc_factory.assembly import (
        _normalize_grader_middleware,
        _normalize_injected_middleware,
        _normalize_subagent_middleware,
    )

    normalizers = {
        "main": _normalize_injected_middleware,
        "subagents": _normalize_subagent_middleware,
        "grader": _normalize_grader_middleware,
    }

    per_target: dict[str, Any] = {}
    if isinstance(result, Mapping):
        keys = set(result)
        targets = keys & set(normalizers)
        if targets and targets != keys:
            msg = (
                f"{MIDDLEWARE_REF_ENV}: {ref!r} returned a mapping mixing "
                f"target keys {sorted(targets)} with {sorted(keys - targets)}. "
                f"Return either a target-keyed mapping "
                f"({sorted(normalizers)}) or a phase-keyed mapping for the "
                f"main agent — not both. Nesting is one level: put phases "
                f"inside a target."
            )
            raise ValueError(msg)
        if targets:
            per_target = dict(result)

    if not per_target:
        # No target keys: the whole value addresses the main agent, in either
        # of the two original forms. Unknown phase keys are caught below by the
        # main normalizer, whose message already lists the valid phases.
        per_target = {"main": result}

    resolved: dict[str, Any] = {}
    for target, normalize in normalizers.items():
        supplied = per_target.get(target)
        try:
            resolved[target] = normalize(supplied)
        except ValueError as exc:
            msg = (
                f"{MIDDLEWARE_REF_ENV}: {ref!r} returned unusable middleware "
                f"for target {target!r}: {exc}"
            )
            raise ValueError(msg) from exc
    return resolved


def _factory_middleware() -> Any:  # noqa: ANN401
    """Resolve caller-supplied middleware from the environment, if any.

    Returns:
        Per-target normalized middleware (see `_normalize_targets`), or
        ``None`` when the variable is unset or empty — which composes exactly
        as it did before the seam existed.
    """
    ref = os.environ.get(MIDDLEWARE_REF_ENV, "").strip()
    if not ref:
        return None
    return _resolve_middleware_ref(ref)


def _print_startup_error(message: str) -> None:
    """Print a startup error for both humans and the parent app process.

    Args:
        message: Concise startup failure to surface in the parent process.
    """
    print(message, file=sys.stderr)  # noqa: T201  # stderr fallback for logs
    summary = " ".join(message.splitlines()).strip() or "<no message>"
    print(  # noqa: T201  # machine-readable marker consumed by server.py
        f"{_STARTUP_ERROR_MARKER}{summary}",
        file=sys.stderr,
    )


async def _make_graph() -> Any:  # noqa: ANN401
    """Create the factory agent graph from environment-based configuration.

    Port of upstream ``server_graph._make_graph``: reads
    ``DEEPAGENTS_CODE_SERVER_*`` env vars via ``ServerConfig.from_env()``,
    resolves a model, assembles tools (reusing upstream's ``_build_tools``,
    which handles MCP discovery on the server loop), and compiles the agent
    graph via ``create_factory_agent``.

    Returns:
        Compiled LangGraph agent graph.
    """
    from lc_factory.assembly import create_factory_agent

    config = ServerConfig.from_env()

    # Offload cwd/path resolution and the lazy settings bootstrap off the event
    # loop. On Windows, `Path.resolve()` / `Path.cwd()` call `os.getcwd()`, which
    # `blockbuster` rejects when invoked directly from the server loop (see
    # issue #5043). Importing `deepagents_code.agent` / first `settings` access
    # can also trigger `find_project_root()` -> `Path.cwd()`.
    #
    # Keep LangSmith redaction configuration on the server task: its fail-closed
    # path calls `langsmith.configure(enabled=False)`, which sets both a global
    # fallback and the current `_TRACING_ENABLED` ContextVar. `asyncio.to_thread`
    # only updates a copied worker context, so a ContextVar disable there would
    # not reach a parent tracing context that already has `enabled=True` (ContextVar
    # wins over the global flag).
    #
    # Divergence from upstream's shape: the boundary is imported at module
    # scope (see module docstring), so the worker returns only the resolved
    # project context rather than upstream's tuple of lazily imported symbols.
    def _resolve_project_context_and_settings() -> ProjectContext | None:
        project_context = get_server_project_context()

        if project_context is not None:
            settings.reload_from_environment(start_path=project_context.user_cwd)
        return project_context

    project_context = await asyncio.to_thread(_resolve_project_context_and_settings)
    configure_langsmith_secret_redaction()

    # Resolved before the model is built so a bad reference fails in a second
    # rather than after provider setup. A failure here must stop the server:
    # booting without the caller's middleware would serve a differently
    # composed agent than they asked for, silently.
    try:
        injected_middleware = _factory_middleware()
    except ValueError as exc:
        logger.exception("Invalid %s", MIDDLEWARE_REF_ENV)
        _print_startup_error(str(exc))
        sys.exit(1)

    # Offload to a worker thread: `create_model` does blocking disk IO for
    # some providers, which `blockbuster` rejects on the server event loop.
    result = await asyncio.to_thread(
        create_model,
        config.model,
        extra_kwargs=config.model_params,
        profile_overrides=config.profile_overrides,
    )
    result.apply_to_settings()

    tools, mcp_server_info, mcp_tools = await _build_tools(config, project_context)
    read_only_context_tools = _criteria_context_tools(tools, mcp_tools)

    # Sandbox lifetime is process-scoped: the context manager is held in
    # module globals and cleaned up via atexit, exactly as upstream does.
    global _sandbox_cm, _sandbox_backend  # noqa: PLW0603
    sandbox_backend = None
    if config.sandbox_type:
        try:
            _sandbox_cm = create_sandbox(
                config.sandbox_type,
                sandbox_id=config.sandbox_id,
                snapshot_name=config.sandbox_snapshot_name,
                setup_script_path=config.sandbox_setup,
            )
            _sandbox_backend = _sandbox_cm.__enter__()  # noqa: PLC2801  # Context manager kept open for server process lifetime
            sandbox_backend = _sandbox_backend

            def _cleanup_sandbox() -> None:
                if _sandbox_cm is not None:
                    _sandbox_cm.__exit__(None, None, None)

            atexit.register(_cleanup_sandbox)
        except ImportError:
            logger.exception(
                "Sandbox provider '%s' is not installed", config.sandbox_type
            )
            _print_startup_error(
                f"Sandbox provider '{config.sandbox_type}' is not installed"
            )
            sys.exit(1)
        except NotImplementedError:
            logger.exception("Sandbox type '%s' is not supported", config.sandbox_type)
            _print_startup_error(
                f"Sandbox type '{config.sandbox_type}' is not supported"
            )
            sys.exit(1)
        except ValueError as exc:
            logger.exception(
                "Invalid sandbox configuration for '%s'", config.sandbox_type
            )
            _print_startup_error(f"Invalid sandbox configuration: {exc}")
            sys.exit(1)
        except Exception as exc:
            logger.exception("Sandbox creation failed for '%s'", config.sandbox_type)
            _print_startup_error(
                f"Sandbox creation failed for '{config.sandbox_type}': {exc}"
            )
            sys.exit(1)

    def _create_factory_agent_sync() -> Any:  # noqa: ANN401
        # `None` when the variable is unset; `.get` then yields `None` per
        # target, which is exactly the inert default each parameter documents.
        targets = injected_middleware or {}
        async_subagents = load_async_subagents() or None
        auto_mode_enabled = config.interactive and sandbox_backend is None

        # These process-global settings writes are safe here because
        # `make_graph` is lock-serialized and caches one graph for the server
        # process lifetime.
        if config.interpreter_ptc is not None:
            settings.interpreter_ptc = config.interpreter_ptc
        if config.interpreter_ptc_acknowledge_unsafe:
            settings.interpreter_ptc_acknowledge_unsafe = True
        if config.enable_interpreter:
            settings.enable_interpreter = True

        agent, _composite_backend = create_factory_agent(
            model=result.model,
            assistant_id=config.assistant_id,
            tools=tools,
            mcp_tools=mcp_tools,
            sandbox=sandbox_backend,
            sandbox_type=config.sandbox_type,
            system_prompt=config.system_prompt,
            interactive=config.interactive,
            auto_approve=config.auto_approve,
            auto_mode_enabled=auto_mode_enabled,
            interrupt_shell_only=config.interrupt_shell_only,
            shell_allow_list=config.shell_allow_list,
            fs_tools=config.allow_fs_tools,
            enable_ask_user=config.enable_ask_user,
            enable_memory=config.enable_memory,
            memory_auto_save=is_memory_auto_save_enabled(),
            enable_skills=config.enable_skills,
            enable_shell=config.enable_shell,
            enable_interpreter=config.enable_interpreter,
            rubric_model=config.rubric_model,
            rubric_max_iterations=config.rubric_max_iterations,
            auto_classifier_model=config.auto_classifier_model,
            recursion_limit=config.recursion_limit,
            mcp_server_info=mcp_server_info,
            cwd=project_context.user_cwd if project_context is not None else config.cwd,
            project_context=project_context,
            async_subagents=async_subagents,
            goal_criteria_tools=read_only_context_tools,
            rubric_grader_tools=read_only_context_tools,
            # All three targets, so a capability that exists in the factory is
            # actually reachable from `lc-code`. Passing only `middleware=`
            # here is what left Group 3's subagent and grader seams usable by
            # nothing (decisions.md D4 rejects a library-only API).
            middleware=targets.get("main"),
            subagent_middleware=targets.get("subagents"),
            rubric_grader_middleware=targets.get("grader"),
        )
        return agent

    return await asyncio.to_thread(_create_factory_agent_sync)


make_graph = _build_graph_factory(_make_graph)
