import type { Interrupt, Message } from './protocol.ts';
export type Scenario = 'working' | 'approval' | 'question' | 'complete' | 'failure';
export function previewScenario(scenario: Scenario): { messages: Message[]; interrupts: Interrupt[]; running: boolean } {
  const messages: Message[] = [
    { id: 'sample-user', type: 'human', content: 'Review the project instructions and make the guidance easier to follow.' },
    { id: 'sample-read', type: 'ai', content: 'I’ll read the project instructions and their linked guides, then identify the changes that would help an agent use them.', tool_calls: [{ id: 'read-1', name: 'read_file', args: { file_path: 'AGENTS.md' } }, { id: 'read-2', name: 'read_file', args: { file_path: 'guides/working-with-memory.md' } }] },
    { id: 'sample-result-1', type: 'tool', tool_call_id: 'read-1', status: 'success', content: '# Project instructions\n\nRead the memory guide before updating project notes.\nKeep the source of each decision with the note.' },
    { id: 'sample-result-2', type: 'tool', tool_call_id: 'read-2', status: 'success', content: '# Working with memory\n\nProject guidance describes how the agent works. Generated notes preserve the outcomes of its work.' },
  ];
  const reason: Message = { id: 'sample-reasoning', type: 'ai', content: '', additional_kwargs: { reasoning_content: 'These examples illustrate provider-exposed reasoning. The instructions describe the right concepts, but the order of operations is unclear. I can make the entry point easier to follow by separating what to read from what to save, and preserving links to the detailed guides.' } };
  const action = { id: 'write-1', name: 'edit_file', args: { file_path: 'AGENTS.md', old_string: 'Read the memory guide before updating project notes.', new_string: 'Before updating project notes:\n1. Read guides/working-with-memory.md.\n2. Check whether an existing note already covers the decision.\n3. Record the outcome and link to its source.' }, description: 'Clarify the order of operations while preserving the existing guidance and its links.' };
  if (scenario === 'working') return { messages: [...messages, reason], interrupts: [], running: true };
  if (scenario === 'approval') return { messages: [...messages, { ...reason, content: 'The guidance is consistent. I’d make the entry point more explicit with a short sequence of steps.', tool_calls: [action] }], interrupts: [{ id: 'sample-approval', value: { action_requests: [action], review_configs: [{ action_name: 'edit_file', allowed_decisions: ['approve', 'reject'] }] } }], running: false };
  if (scenario === 'question') return { messages: [...messages, { id: 'sample-question-intro', type: 'ai', content: 'I found two useful ways to organize the guidance. Which would fit how you work?' }], interrupts: [{ id: 'sample-question', value: { type: 'ask_user', questions: [{ question: 'How would you like the guidance organized?', type: 'multiple_choice', choices: [{ value: 'By workflow' }, { value: 'By type of information' }] }] } }], running: false };
  if (scenario === 'failure') return { messages: [...messages, { id: 'sample-test-call', type: 'ai', content: 'I’ll check the documentation links before proposing a change.', tool_calls: [{ id: 'check-1', name: 'execute', args: { command: 'npm run check:links' } }] }, { id: 'sample-test-error', type: 'tool', tool_call_id: 'check-1', status: 'error', content: 'Link check failed\n\nAGENTS.md:12 → guides/archive.md\nTarget does not exist.\n\n1 broken link found.' }, { id: 'sample-failure-answer', type: 'ai', content: 'The link check found a broken reference to `guides/archive.md`.\n\nI’ll need to locate the intended guide before changing that link. The two guides I could read are otherwise consistent.' }], interrupts: [], running: false };
  return { messages: [...messages, { ...reason, content: 'The entry point would benefit from a short checklist.' }, { id: 'sample-final', type: 'ai', content: 'The instructions already have a useful separation between **agent guidance** and **generated notes**. I’d make that distinction easier to act on.\n\n### Three targeted improvements\n\n1. **Start with a short checklist.** Make the reading order and update steps explicit.\n2. **Keep extended guidance linked.** Let the agent load details when they are relevant.\n3. **Record decisions with their sources.** Make saved notes easier to trust and revisit.\n\n| Keep in the instructions | Keep in project notes |\n| --- | --- |\n| How to perform the work | What the work produced |\n| Links to relevant guides | Decisions and their sources |\n\nThese changes can clarify the workflow while keeping the existing files as the source of truth.' }], interrupts: [], running: false };
}
